pipeline:

  publish:
    image: plugins/docker
    registry: walmartdigital.azurecr.io
    repo: walmartdigital.azurecr.io/look-and-pay-frontend
    tags:
      - latest
      - c-${DRONE_COMMIT_SHA}
      - b-${DRONE_BUILD_NUMBER}
    secrets: [ docker_username, docker_password ]
    when:
      event: [push, pull_request, tag]
      branch: master

  slack:
      image: plugins/slack
      webhook: https://hooks.slack.com/services/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
      icon_emoji: ':robot_face:'
      when:
        status: [success, failure]
      template: >
        {{#success build.status}}
          [{{repo.name}}] @{{build.author}} build {{build.number}} succeeded. Good job. :party_parrot:
        {{else}}
          [{{repo.name}}] @{{build.author}} build {{build.number}} failed. Fix me please. :fire:
        {{/success}}
